
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/clion/261/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.2.0-39-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/snap/clion/261/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/clion/261/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/clion/261/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/cc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/natasa/Desktop/Fakultet/4.god/7.sem/asp_review/DOMACI/cmake-build-debug/CMakeFiles/3.27.8/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/clion/261/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/clion/261/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/clion/261/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/c++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/natasa/Desktop/Fakultet/4.god/7.sem/asp_review/DOMACI/cmake-build-debug/CMakeFiles/3.27.8/CompilerIdCXX/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/snap/clion/261/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/snap/clion/261/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/natasa/Desktop/Fakultet/4.god/7.sem/asp_review/DOMACI/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ZDjDPT"
      binary: "/home/natasa/Desktop/Fakultet/4.god/7.sem/asp_review/DOMACI/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ZDjDPT"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/natasa/Desktop/Fakultet/4.god/7.sem/asp_review/DOMACI/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ZDjDPT'
        
        Run Build Command(s): /snap/clion/261/bin/cmake/linux/x64/bin/cmake -E env VERBOSE=1 /usr/bin/cmake -f Makefile cmTC_f5ee1/fast
        CMake Error: Unknown argument -f
        CMake Error: Run 'cmake --help' for all supported options.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/snap/clion/261/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: /usr/bin/cc"
    directories:
      source: "/home/natasa/Desktop/Fakultet/4.god/7.sem/asp_review/DOMACI/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-f3Ad4V"
      binary: "/home/natasa/Desktop/Fakultet/4.god/7.sem/asp_review/DOMACI/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-f3Ad4V"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/home/natasa/Desktop/Fakultet/4.god/7.sem/asp_review/DOMACI/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-f3Ad4V'
        
        Run Build Command(s): /snap/clion/261/bin/cmake/linux/x64/bin/cmake -E env VERBOSE=1 /usr/bin/cmake -f Makefile cmTC_1ad05/fast
        CMake Error: Unknown argument -f
        CMake Error: Run 'cmake --help' for all supported options.
        
      exitCode: 1
...
